# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:6
      
    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: npm test

      - run: docker build -t 18fcli .
      - run:
          name: Integration test for license
          command: |
            docker run --name license --entrypoint yo 18fcli 18f:license
            docker cp license:/workdir /tmp/license
            [ -f /tmp/license/LICENSE.md ]
      - run:
          name: Integration test for README
          command: |
            echo "ANew ProjProj" | docker run --name readme -i --entrypoint yo 18fcli 18f:readme
            docker cp readme:/workdir /tmp/readme
            grep "ANew ProjProj" /tmp/readme/README.md

  publish:
    docker:
      # specify the version you desire here
      - image: circleci/node:6  

    steps:
      - attach_workspace:
          at: ~/repo

      - run: 
          name: Write NPM Token to ~/.npmrc
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc

      - run:
          name: Publish to NPM
          command: npm publish --access=public

workflows:
  version: 2

  build_and_maybe_publish:
    jobs:
      - build
      - publish:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
          requires:
            - build
